### ISSUE TITLE
对于blank类的问题

### ISSUE THREAD

**Issue by BigTree765** [ReverseSystem001/crnn_centerloss_pytorch#1]
你好，对于blank有什么特殊的操作吗，在预测时，大部分样本都会预测为blank类，这是一个样本不均衡的问题。

**Comment by ReverseSystem001** [comment]
可以参考raw_pred_to_features函数中的处理逻辑，blank是直接给去掉的，预测跟样本不均衡有啥关系...

**Comment by BigTree765** [comment]
因为blank大量存在的话，我觉得可能会导致正则项都加在了blank
上
在2022年3月9日 ***@***.***> 写道：

可以参考raw_pred_to_features函数中的处理逻辑，blank是直接给去掉的，预测跟样本不均衡有啥关系...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ReverseSystem001** [comment]
你说的正则项指的是BN？

**Comment by BigTree765** [comment]
还有就是那个形近字的数据集还有吗



因为blank大量存在的话，我觉得可能会导致正则项都加在了blank
上
在2022年3月9日 ***@***.***> 写道：

可以参考raw_pred_to_features函数中的处理逻辑，blank是直接给去掉的，预测跟样本不均衡有啥关系...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ReverseSystem001** [comment]
> 还有就是那个形近字的数据集还有吗 因为blank大量存在的话，我觉得可能会导致正则项都加在了blank 上 在2022年3月9日 ***@***.***> 写道： 可以参考raw_pred_to_features函数中的处理逻辑，blank是直接给去掉的，预测跟样本不均衡有啥关系... — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

我是在网上找了形近字字典，然后生成的一批数据，你可以在网上搜下形近字，有很多，或者过两天我找找把形近字字典传上去

**Comment by ReverseSystem001** [comment]
> 因为blank大量存在的话，我觉得可能会导致正则项都加在了blank 上 在2022年3月9日 ***@***.***> 写道： 可以参考raw_pred_to_features函数中的处理逻辑，blank是直接给去掉的，预测跟样本不均衡有啥关系... — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

不太理解你说的什么意思，你是为了解决什么问题吗？

**Comment by BigTree765** [comment]
谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小，不知道这会不会影响性能。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。

**Comment by ReverseSystem001** [comment]
处理流程center loss blank是会去掉的，形近字测试集是用形近字生成的.正常训练都是全量数据(包括形近字)生成的训练集文本行，tensor flow那个版本应该是只生成了一个字的文本，生成脚本生成字的个数是可以确定的，这个没什么可疑虑的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)




 
谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BigTree765** [comment]
我说一下我的理解，您看一下对吗，tensorflow的那个版本相当于先用全集数据进行训练（文本行），测试的时候运用形近字的单字进行测试，然后得到单字的位置和特征，然后做了可视化。


在2022年3月9日 ***@***.***> 写道：

处理流程center loss blank是会去掉的，形近字测试集是用形近字生成的.正常训练都是全量数据(包括形近字)生成的训练集文本行，tensor flow那个版本应该是只生成了一个字的文本，生成脚本生成字的个数是可以确定的，这个没什么可疑虑的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)





谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BigTree765** [comment]
我还想问一下两种方案，各有什么利弊吗，有没有一个比较好的比较


在2022年3月9日 ***@***.***> 写道：
我说一下我的理解，您看一下对吗，tensorflow的那个版本相当于先用全集数据进行训练（文本行），测试的时候运用形近字的单字进行测试，然后得到单字的位置和特征，然后做了可视化。


在2022年3月9日 ***@***.***> 写道：

处理流程center loss blank是会去掉的，形近字测试集是用形近字生成的.正常训练都是全量数据(包括形近字)生成的训练集文本行，tensor flow那个版本应该是只生成了一个字的文本，生成脚本生成字的个数是可以确定的，这个没什么可疑虑的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)





谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BigTree765** [comment]
我说一下我的一些疑惑啊。
百度方案： 采用每个时间步的预测加center_loss
阿里方案： 只选择预测个数跟标签个数相等的样本，计算center_loss, 计算时只计算字符类，重复字符只取最后一个时间步计算center_loss。 我觉得这个会存在着预测跟标签数目相等，但是预测结果跟真实结果不匹配的情况。 另外这个重复字符选择最右侧，我觉得选择最中间的感觉合理一些。


在2022年3月9日 ***@***.***> 写道：
我还想问一下两种方案，各有什么利弊吗，有没有一个比较好的比较


在2022年3月9日 ***@***.***> 写道：
我说一下我的理解，您看一下对吗，tensorflow的那个版本相当于先用全集数据进行训练（文本行），测试的时候运用形近字的单字进行测试，然后得到单字的位置和特征，然后做了可视化。


在2022年3月9日 ***@***.***> 写道：

处理流程center loss blank是会去掉的，形近字测试集是用形近字生成的.正常训练都是全量数据(包括形近字)生成的训练集文本行，tensor flow那个版本应该是只生成了一个字的文本，生成脚本生成字的个数是可以确定的，这个没什么可疑虑的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)





谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***&gt;

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ReverseSystem001** [comment]
嗯，所以说百度方案比较暴力嘛。我当时问了tensor flow作者为什么用最右侧的，他没回答，猜测原因是：可能很多情况预测的时候，重复字符也就那么一两个，这个可以自己找一批图，把原始重复ID打印一下看一看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)




 我说一下我的一些疑惑啊。
 百度方案： 采用每个时间步的预测加center_loss
 阿里方案： 只选择预测个数跟标签个数相等的样本，计算center_loss, 计算时只计算字符类，重复字符只取最后一个时间步计算center_loss。 我觉得这个会存在着预测跟标签数目相等，但是预测结果跟真实结果不匹配的情况。 另外这个重复字符选择最右侧，我觉得选择最中间的感觉合理一些。
 
 
 在2022年3月9日 ***@***.***&gt; 写道：
 我还想问一下两种方案，各有什么利弊吗，有没有一个比较好的比较
 
 
 在2022年3月9日 ***@***.***&gt; 写道：
 我说一下我的理解，您看一下对吗，tensorflow的那个版本相当于先用全集数据进行训练（文本行），测试的时候运用形近字的单字进行测试，然后得到单字的位置和特征，然后做了可视化。
 
 
 在2022年3月9日 ***@***.***&gt; 写道：
 
 处理流程center loss blank是会去掉的，形近字测试集是用形近字生成的.正常训练都是全量数据(包括形近字)生成的训练集文本行，tensor flow那个版本应该是只生成了一个字的文本，生成脚本生成字的个数是可以确定的，这个没什么可疑虑的
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2022年3月9日(周三) 晚上7:09
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)
 
 
 
 
 
 谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ReverseSystem001** [comment]
其实还有第三种方案，我没尝试，这个得根据自己训练集来看，目前自己测试的只有利没有弊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月9日(周三) 晚上8:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)




 我还想问一下两种方案，各有什么利弊吗，有没有一个比较好的比较
 
 
 在2022年3月9日 ***@***.***&gt; 写道：
 我说一下我的理解，您看一下对吗，tensorflow的那个版本相当于先用全集数据进行训练（文本行），测试的时候运用形近字的单字进行测试，然后得到单字的位置和特征，然后做了可视化。
 
 
 在2022年3月9日 ***@***.***&gt; 写道：
 
 处理流程center loss blank是会去掉的，形近字测试集是用形近字生成的.正常训练都是全量数据(包括形近字)生成的训练集文本行，tensor flow那个版本应该是只生成了一个字的文本，生成脚本生成字的个数是可以确定的，这个没什么可疑虑的
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2022年3月9日(周三) 晚上7:09
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [ReverseSystem001/crnn_centerloss_pytorch] 对于blank类的问题 (Issue #1)
 
 
 
 
 
 谢谢你啊，我只是大部分时间步的预测结果都为blank，centerloss都加在了blank上，对于字符类预测的个数相对比较小。还有就是crnn不是训练文本行吗，是用形近字生成了文本行吗，我看tensorflow版本的有一个在特征空间的嵌入图，我对这个图如何得到单字的有些困惑。
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shengyudingli** [comment]
> 话说第三种方案是啥？
